version: 0.0
os: linux
files:
  - source: /
    destination: /var/api/
hooks:
  AfterInstall:
    - location: script/npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: script/npm-start.sh
      runas: root
      timeout: 60