version: 0.0
os: linux
files:
  - source: /
    destination: /var/api/
hooks:
  AfterInstall:
    - location: script/install
      runas: root
      timeout: 300
  ApplicationStart:
    - location: script/start
      runas: root
      timeout: 60